### ISSUE TITLE
6th email followup

### ISSUE THREAD

**Issue by jo5hs** [richardjortega/grapevine#4]
Need to work on logic for sending the 6th email after users have already received their 5th and final review:
1. On a specific day of the month?
2. X number of days from when they received their last review?
3. When a 6th review comes in, send the 'you missed it' email?

We also need to rough out what this email should say and how we should say it. Erik made a comment last week about saying it in a way that doesn't suggest we'll send them any emails missed through the time that they were free till they upgraded.

cc/ @Thor74 @richardjortega

**Comment by richardjortega** [comment]
first. gay gay.
